//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace lifesenseSystem.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class lifesenseEntities : DbContext
    {
        public lifesenseEntities()
            : base("name=lifesenseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<t_configinfo> t_configinfo { get; set; }
        public DbSet<t_heartrateinfo> t_heartrateinfo { get; set; }
        public DbSet<t_sleepinfo> t_sleepinfo { get; set; }
        public DbSet<t_userinfo> t_userinfo { get; set; }
        public DbSet<t_walkinfo> t_walkinfo { get; set; }
        public DbSet<t_admin> t_admin { get; set; }
    }
}
